"""empty message

Revision ID: 910ad6f842c5
Revises: fa1956c3553a
Create Date: 2021-02-20 03:14:34.249299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910ad6f842c5'
down_revision = 'fa1956c3553a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
